image: maven:latest

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"
  
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.clean.skip=true compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  when: manual
