image: maven:latest

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"
  
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

stages:
  - lintandbuild
  - verify
  - deploy

lint:
  stage: lintandbuild
  script:
    - mvn $MAVEN_CLI_OPTS checkstyle:check
  allow_failure: true

build:
  stage: lintandbuild
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.clean.skip=true compile
  artifacts:
    paths:
      - target/
    expire_in: 1h

verify:
  stage: verify
  dependencies:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  when: manual
